name: E2E
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-actions@v3
        with:
          browser: chrome
          build: npm build
          start: npm start
          wait-on: "http://localhost:3000"
